### ISSUE TITLE
Shows nothing after loading data

### ISSUE THREAD

**Issue by singh-hrituraj** [cbaziotis/neat-vision#1]
I loaded a .json file to visualise the attention. I wanted to visualise it in the context of regression. Nothing came as output. 
Here is the format which I used:

`{
	"text":	["t","ewcom","producers","announced"]
	"label": 0,
	"prediction": 0,
	"attention": [0.17704035,0.7129273,0.23426278,0.53958344]
}`

I am using only one example though. Does it have anything to do with that?

The screen just did not show anything - like no change occured.

**Comment by skychwang** [comment]
I'm also getting this error, but I think I've found the reason: you need more than 1 input into the file. If you, say, duplicate it once, add a comma to separate them, and surround it with a [], like such:

`[{ "text": ["t","ewcom","producers","announced"] "label": 0, "prediction": 0, "attention": [0.17704035,0.7129273,0.23426278,0.53958344] }, { "text": ["t","ewcom","producers","announced"] "label": 0, "prediction": 0, "attention": [0.17704035,0.7129273,0.23426278,0.53958344] }]`

It will work.
This bug needs to be fixed though.

**Comment by singh-hrituraj** [comment]
Ah! I see. It is working with multiple inputs. 

I anyway need it for multiple inputs. So, Thanks!
